services:
  database:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  flask_server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - database
    ports:
      - 5000:5000
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    # command: 
# ["flask", "--app", "src/flask_app/app.py", "run", "--host", "0.0.0.0"]