services:
  database:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  flask_server:
    image: flask_test_image
    restart: always
    depends_on:
      - database
    ports:
      - 5000:5000

